새로 환경 설정을 하면 주피터 노트북도 실행이 안 되며, 도커 설치 조차 되어 있지 않다.
베이스에 설치를 해도, 도커 컨테이너에 설치하여 해당 위치에서 작업을 하기에 아무런 작업을 하지 않고 도커부터 작업을 진행한다.

 set up the repository
 - https를 통해 repository를 사용할 수 있도록 패키지 설치.
 https://velog.io/@boom109/Nvidia-docker

설치 후에 도커 이미지를 검색하기 위해 https://hub.docker.com/ 로 가서 이미지 찾은 후, 컨테이너 생성
https://hanseokhyeon.tistory.com/entry/Docker%EB%A1%9C-%EB%94%A5%EB%9F%AC%EB%8B%9D%ED%95%98%EA%B8%B0-Pytorch

docker run -itd --name container_1 -v /home:/home  -w /home/ubuntu/hm --gpus all --restart=always <이미지id> /bin/bash

nvidia 도커는 gpu를 위해 꼭 설치해야한다.

### 주피터 노트북 셋팅과정

1. extension에서 python 설치
2. extension에서 jupyter 설치
3. cmd에서 torch 설치

In [2]:
# gpu 확인
!lspci | grep -i nvidia

/bin/bash: lspci: command not found


#### cpu,gpu 연결 도움 링크 
#### https://jimmy-ai.tistory.com/224

###  도커 설치 과정

In [1]:
!nvidia-smi 
# nvidia 드라이버 확인
!nvcc -V 
# cuda 확인
!ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep libcudnn 
#cudnn 확인

Wed Dec 28 18:11:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0    66W / 149W |      0MiB / 11441MiB |     94%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

--------------------------------------------------
위까지는 셋팅 지금부터 테스트

In [2]:
import torch

In [3]:
print(torch.cuda.is_available())
# GPU 사용 가능 -> 가장 빠른 번호 GPU, GPU 사용 불가 -> CPU 자동 지정 예시
device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

True


In [4]:
data = torch.randn(2,3)

In [5]:
print(data)
print(data+data)
print(data*5)
print(data.shape)
print(data.dtype)

tensor([[ 2.6865, -1.2549, -0.5835],
        [-0.0693, -0.6965, -0.3044]])
tensor([[ 5.3730, -2.5099, -1.1671],
        [-0.1385, -1.3931, -0.6088]])
tensor([[13.4326, -6.2747, -2.9177],
        [-0.3463, -3.4827, -1.5220]])
torch.Size([2, 3])
torch.float32


In [6]:
lst1 = [1,2]
lst2 = [3,4]

tor1 = torch.tensor([1,2])
tor2 = torch.tensor([3,4])

print(lst1+lst2)
print(tor1+tor2)
print(tor1+lst2)

[1, 2, 3, 4]
tensor([4, 6])


TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'